workflow revision

diff --git a/.github/workflows/create-docker-hub-image.yml b/.github/workflows/create-docker-hub-image.yml
--- a/.github/workflows/create-docker-hub-image.yml
+++ b/.github/workflows/create-docker-hub-image.yml
@@ -18,7 +18,14 @@ jobs:
 
       - name: Set Tag
         id: set_tag
-        run: echo "IMAGE_TAG=$(echo $GITHUB_REF | sed -n 's/refs\/tags\/v\\([0-9]*.[0-9]*.[0-9]*\\)/\\1/p')" >> $GITHUB_ENV
+        run: |
+          TAG=$(echo $GITHUB_REF | sed -n 's/refs\/tags\/v\\([0-9]*.[0-9]*.[0-9]*\\)/\\1/p')
+          if [ -n "$TAG" ]; then
+            echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
+          else
+            echo "Error: Couldn't extract tag from GITHUB_REF"
+          exit 1
+          fi
 
       - name: Docker meta
         id: meta
